GH Action: Run tests and check file existance

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -30,10 +30,14 @@ jobs:
         run: npx eslint .
       - name: Lint test.ts
         run: (cd packages/node && npx tsc -p ./tsconfig.lint-test.json)
+      - name: Run Tests
+        run: |
+          npm run test
+          test -f packages/node/dist/qrcode.png || {echo "File not found"; exit 1}
       - name: Run cli and test it
         run: |
           node packages/node/lib/cli.js --opt.color white --opt.finder.round 0.5 qrcode-cli.png
-          test -f qrcode-cli.png || exit 1
+          test -f qrcode-cli.png || {echo "File not found"; exit 1}
       - name: Run update-readme
         run: npm run update-readme
       - name: Run prettier on Readmes
